### PR TITLE
Fixed annoying valgrind false positive

### PR DESCRIPTION
**Pull request by osleg**
* Initialized act.sa_flags to 0
* Initialized act.sa_mask to empty set
** Vim cleaned up all whitespaces around the file -_-

### CODE REVIEW

**Comment by Pithikos** [comment]
Hi,

is there a way to reproduce the valgrind false positive that you mention?

**Comment by osleg** [comment]
It's caused in conjuction with libxml2,
I will try to narrow it down for a test case but I'm afraid I will be able to free time for this only in a week

**Comment by Pithikos** [comment]
Oh, that is fine. Do it when you can. It's just good to have a test case just so the bug doesn't reoccur in the future.

**Comment by Pithikos** [comment]
Thanks for the contribution osleg. In the end however I merged @895d08c instead since it did not include the whitespace changes. Cheers!

**Pull request closed without merging**
